### ISSUE TITLE
Compatible with powerline?

### ISSUE THREAD

**Issue by jcs090218** [terlar/indent-info.el#12]
I just installed the package and get very excited about how this package can change my life. I put the config as shown in the README file but nothing happens, not even a single error.
```
(require 'indent-info)
(global-indent-info-mode +1)
```

My first thought is the package `powerline` is interfering this package. Indeed, after I disabled package `powerline` the package seems to work! 

Is this something that you could fix? 

Thank you for all you hard work!

**Comment by terlar** [comment]
Hello and thank you for your enthusiastic feedback.

It is quite flexible and all it does is appending this to a list, by default it prepends it to the mode-line-position which is in the mode-line by default. I am guessing powerline removes it and creates it's own mode-line-format. You can inspect your mode-line-format and see if there is any list there you could target instead. You do this via indent-info-insert-target. In worst case I guess you could try to use mode-line-format as target. You can control the position via indent-info-insert-position.

These variables are customizable with customize or setq.

See:
https://github.com/terlar/indent-info.el/blob/master/indent-info.el#L41

I am out travelling now, so I won't have time to present a solution at the time.

Please let me know how it goes.

**Comment by jcs090218** [comment]
Hi, sorry to disturb you while you are traveling. I have tried some of the methods you mentioned, I would have to say that I am not very familiar with `mode-line-format`, or anything else related to `mode-line`. I reckon I would not have adequate knowledge to resolve this issue, on the other hand, I would endeavor to address it. I am not quite sure how am I able to alter or inspect `mode-line-format` to achieve this, but at least I tried changing the `indent-info-insert-position`. Conclude not working.

**Comment by terlar** [comment]
No worries, it just means I am without computer for the moment.

mode-line-format is just a variable you can inspect it by running C-h v (describe-variable). It is just a list describing how the mode-line should look like. Usually it is a bunch of variables that themselves are lists therefore you should be able to target either of those lists where indent-info should be added. It could either be one of those variables occurring in your mode-line or the variable mode-line-format itself.

You can read more about it here:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Mode-Line-Basics.html

**Comment by terlar** [comment]
Forgot about this one, did you find a solution or did you move on, not needing the package?

**Comment by jcs090218** [comment]
I move on because I don't know much about the package `powerline`. :( You can close this issue if you want!

**Comment by terlar** [comment]
In case someone else runs into this.

By default the mode-line looks like this when using `powerline`:
```emacs-lisp
("%e"
 (:eval
   (let*
       ((active
	 (powerline-selected-window-active))
	(mode-line-buffer-id
	 (if active 'mode-line-buffer-id 'mode-line-buffer-id-inactive))
	(mode-line
	 (if active 'mode-line 'mode-line-inactive))
	(face0
	 (if active 'powerline-active0 'powerline-inactive0))
	(face1
	 (if active 'powerline-active1 'powerline-inactive1))
	(face2
	 (if active 'powerline-active2 'powerline-inactive2))
	(separator-left
	 (intern
	  (format "powerline-%s-%s"
		  (powerline-current-separator)
		  (car powerline-default-separator-dir))))
	(separator-right
	 (intern
	  (format "powerline-%s-%s"
		  (powerline-current-separator)
		  (cdr powerline-default-separator-dir))))
	(lhs
	 (list
	  (powerline-raw "%*" face0 'l)
	  (when powerline-display-buffer-size
	    (powerline-buffer-size face0 'l))
	  (when powerline-display-mule-info
	    (powerline-raw mode-line-mule-info face0 'l))
	  (powerline-buffer-id
	   `(mode-line-buffer-id ,face0)
	   'l)
	  (when
	      (and
	       (boundp 'which-func-mode)
	       which-func-mode)
	    (powerline-raw which-func-format face0 'l))
	  (powerline-raw " " face0)
	  (funcall separator-left face0 face1)
	  (when
	      (and
	       (boundp 'erc-track-minor-mode)
	       erc-track-minor-mode)
	    (powerline-raw erc-modified-channels-object face1 'l))
	  (powerline-major-mode face1 'l)
	  (powerline-process face1)
	  (powerline-minor-modes face1 'l)
	  (powerline-narrow face1 'l)
	  (powerline-raw " " face1)
	  (funcall separator-left face1 face2)
	  (powerline-vc face2 'r)
	  (when
	      (bound-and-true-p nyan-mode)
	    (powerline-raw
	     (list
	      (nyan-create))
	     face2 'l))))
	(rhs
	 (list
	  (powerline-raw global-mode-string face2 'r)
	  (funcall separator-right face2 face1)
	  (unless window-system
	    (powerline-raw
	     (char-to-string 57505)
	     face1 'l))
	  (powerline-raw "%4l" face1 'l)
	  (powerline-raw ":" face1 'l)
	  (powerline-raw "%3c" face1 'r)
	  (funcall separator-right face1 face0)
	  (powerline-raw " " face0)
	  (powerline-raw "%6p" face0 'r)
	  (when powerline-display-hud
	    (powerline-hud face0 face2))
	  (powerline-fill face0 0))))
     (concat
      (powerline-render lhs)
      (powerline-fill face2
		      (powerline-width rhs))
      (powerline-render rhs)))))
```

I tried using `(setq indent-info-insert-target 'mode-line-mule-info)` and it works because by default powerline renders this list. This could be done for any list appearing inside the mode-line or call the function `indent-info-mode-line` directly at the appropriate place via `powerline-raw` just like what is done for the `nyan-mode`. E.g.:
```
(when (bound-and-true-p indent-info-mode) (powerline-raw (list (indent-info-mode-line)) face2 'l))
```
