### ISSUE TITLE
Customize position of indent-info-mode-line

### ISSUE THREAD

**Issue by ylluminarious** [terlar/indent-info.el#5]
The position of `indent-info-mode-line` is always near the beginning of the mode-line because of this code in `indent-info-mode`:

```elisp
(add-to-list 'mode-line-position
                   '(indent-info-mode (:eval (indent-info-mode-line))))
```

`add-to-list`, by default, adds new items to its given list at the front. I would prefer to pick my own position for `indent-info-mode-line`. Could you please add a customization option for that?

**Comment by terlar** [comment]
Thank you for your feedback, I will gladly add the possibility to customize this, any suggestion for how this should be customized?

Like `indent-info-insert-target` and `indent-info-insert-position`?

**Comment by ylluminarious** [comment]
@terlar Thanks for responding so quickly! Either of those would be fine, though `indent-info-insert-position` sounds more fine-grained which I would prefer.

**Comment by terlar** [comment]
The `indent-info-insert-target` I was thinking if you would want it targeted at some other list, that is also something I would consider people wanting. So the default there would be `mode-line-position`.

**Comment by ylluminarious** [comment]
@terlar Oh, ok. That's not a bad idea.

**Comment by terlar** [comment]
This is now possible to customize  through these options:

```
(setq indent-info-insert-target 'mode-line-format)
(setq indent-info-insert-position 'after)
```

This would for example put it at the end of the mode-line.

What you requested would be achieved like:
```
(setq indent-info-insert-position 'after)
```

**Comment by ylluminarious** [comment]
@terlar Thanks a lot! With these two options, this mode is much more customizable and I'm much happier with it now.

**Comment by terlar** [comment]
Glad to hear it is more satisfactory now, thank you for the feedback :+1:
