### ISSUE TITLE
Customize bindings for indent-info-cycle-tab-width-increase & indent-info-cycle-tab-width-decrease

### ISSUE THREAD

**Issue by ylluminarious** [terlar/indent-info.el#6]
I cannot customize the key bindings for `indent-info-cycle-tab-width-increase` or `indent-info-cycle-tab-width-decrease` as they are both dynamically bound in a local variable in `indent-info-mode-line`:

```elisp
(let* ((map
        '(keymap
          (mode-line keymap
                     (mouse-1 . indent-info-toggle-indent-mode)
                     (mouse-4 . indent-info-cycle-tab-width-increase)
                     (mouse-5 . indent-info-cycle-tab-width-decrease))))
       (help "Indentation\n\ mouse-1: Toggle tabs/spaces\n\ mouse-4: Increase tab-width\n\ mouse-5: Decrease tab-width"))
  ...)
```

Please make the bindings for these functions customizable; I cannot trigger `mouse-4` or `mouse-5` events with my mouse.

**Comment by terlar** [comment]
These functions are autoloaded and you can easily add you own custom mappings, like:
`(global-set-key "C-+" 'indent-info-cycle-tab-width-increase)`

But it is still fair to want to change these defaults, especially if they should be operations bound to mouse actions when hovering the mode. Any suggestion how this should be configured? Expose they keymap perhaps? Such as `indent-info-mode-line-map`. The tricky part there is that I rather have the help text be properly reflected also.

**Comment by ylluminarious** [comment]
@terlar An `indent-info-mode-line-map` is what I was thinking, though using `global-set-key` slipped my mind for some reason. If you don't mind implemented `indent-info-mode-line-map`, I'll leave this issue open. Otherwise, I can just use `global-set-key`. Though, it probably wouldn't hurt to add a note to the README which explains how to customize these functions' bindings.

**Comment by terlar** [comment]
I still think it is a good idea, but want to figure out how to map the help text also, when it comes to the mouse based bindings, I could provide a general keymap for the keyboard also, if I can come up with good defaults that doesn't conflict with other things. Let's leave this open for now.

**Comment by ylluminarious** [comment]
@terlar Sounds good 👍

**Comment by terlar** [comment]
The mode-line is now customizable and the following keybindings are setup by default:

| Key              | Action                                 |
| ---------------- | -------------------------------------- |
| <kbd>C-M-~</kbd> | `indent-info-toggle-indent-mode`       |
| <kbd>C-M-></kbd> | `indent-info-cycle-tab-width-increase` |
| <kbd>C-M-<</kbd> | `indent-info-cycle-tab-width-decrease` |

**Comment by ylluminarious** [comment]
@terlar Thanks!
