### ISSUE TITLE
Add more contextual options for easy switching

### ISSUE THREAD

**Issue by terlar** [terlar/indent-info.el#8]
Something like this:

- Introduce menu and add selection options
- Add possibility to convert between spaces/tabs

![spaces-to-spaces-dif](https://user-images.githubusercontent.com/280235/33799946-93612ae8-dd36-11e7-8def-1231691a840c.gif)
![spaces-to-tabs-dif](https://user-images.githubusercontent.com/280235/33799947-937ddbe8-dd36-11e7-88c2-3c67c64d9fd8.gif)
![tabs-to-spaces-dif](https://user-images.githubusercontent.com/280235/33799948-93986792-dd36-11e7-8d00-ec15cc592f8d.gif)
![tabs-to-spaces-same](https://user-images.githubusercontent.com/280235/33799949-93b76160-dd36-11e7-8d00-a3b4246689de.gif)

Source: https://css-tricks.com/changing-spaces-tabs-sublime-text/

**Comment by ylluminarious** [comment]
@terlar Conversion between spaces and tabs should be fairly straightforward via `tabify` and `untabify`. I also have a function which entabs only leading spaces (original idea [here](https://stackoverflow.com/q/11623721/2636454)):

```elisp
(defun tabify-leading (start end)
  "Call `tabify' with `tabify-regexp' set so that only leading
spaces are treated. With prefix arg, call ‘tabify’ with
‘tabify-regexp’ set so that only _the very first_ set of
indentation spaces are treated."
  (interactive "r")
  (require 'tabify)
  (setq tabify-regexp-old tabify-regexp)
  (unwind-protect
      (progn
        (if current-prefix-arg
            (setq tabify-regexp "^\t* [ \t]")
          (setq tabify-regexp "^\t* [ \t]+"))
        (tabify start end))
    (setq tabify-regexp tabify-regexp-old)))
```

**Comment by terlar** [comment]
A bit late, but that whole menu thing was driving me crazy, but recently I found easy-menu which made the thing possible. I have now updated and also implemented the tab/space conversion. Thank you for your snippet.

**Comment by ylluminarious** [comment]
@terlar Thanks, this is pretty cool! Being able to use the mouse there will be convenient when I forget the key bindings from time to time.
